### ISSUE TITLE
How to get started translating IdentityServer3

### ISSUE THREAD

**Issue by svrooij** [johnkors/IdentityServer3.Contrib.Localization#16]
@johnkors you asked me to help translating IdentityServer.
I'm will to do the English => Dutch translation, but I have no clue how to get started.

And I'm wondering if anyone would use the dutch translation. Everyone here, got English as a required subject in high school.

**Comment by johnkors** [comment]
Hi @svrooij !

Good point - I need to add to the readme how to contribute! 

To do the translations, you could see how it's done [in a recent PR](https://github.com/johnkors/IdentityServer3.Contrib.Localization/pull/15/files) by @ManuelRauber  added with adding support for german. Basically, adding some resx files with the correct iso code for dutch, and the translations for each resource text idsrv supports. So for dutch, you would for example copy the german ones and create a resx with a nl-NL.resx suffix. These three files are the ones that need to be "implemented" : `Events.nl-NL.resx` , `Messages.nl-NL.resx` and `Scopes.nl-NL.resx`.

ISO codes : https://msdn.microsoft.com/en-us/library/ee796272%28v=cs.20%29.aspx

Also, there are some unit tests that verify that all ids have translations, so please run these as well. They're also run if you submit a PRs on a CI server (appveyor), so one could tell if they are green or not.

Yep, there is no obligation to use dutch if you don't want to. For people wanting to use a specific language though, a translation would be nice. We have the same requirement in my current project for norwegian, and I think we are on the same level regarding the common level of english within the population in Norway vs Netherlands. We're however creating a norwegian login page where the all texts like "Username and password required." or "Password required" should be in norwegian, if the user wants it. So that's the use case. Hope this helps.

/J

**Comment by johnkors** [comment]
I added a "Contributing" section in the readme. Let me know if you still have some questions.
